"""Category detection and the two rules files (ADR-0009)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from deck_composer.check import in_category
from deck_composer.errors import ToolError
from deck_composer.facts import read as read_facts
from deck_composer.rules import METRIC, VIOLATION, read_rules, read_targets, searchable
from tests.helpers import GOLDEN, KNOWN_POSITIVE, regenerating

CATEGORIES = Path("data/categories.json")
TARGETS = Path("data/targets.json")
POOL = Path("data/card_facts.json")

# What each fixture card is a known positive for. Hand-reviewed once.
EXPECTED = {
    "Time Warp": "extra_turns",
    "Time Stretch": "extra_turns",
    "Temporal Manipulation": "extra_turns",
    "Armageddon": "mass_land_denial",
    "Ruination": "mass_land_denial",
    "Catastrophe": "mass_land_denial",
    "Sol Ring": "ramp",
    "Cultivate": "ramp",
    "Rampant Growth": "ramp",
    "Wrath of God": "sweepers",
    "Swords to Plowshares": "targeted_interaction",
    "Divination": "draw",
}


@pytest.fixture
def rules():
    return read_rules(CATEGORIES)


# --- the patterns the owned pool cannot exercise --------------------------


@pytest.mark.parametrize(("name", "category"), sorted(EXPECTED.items()))
def test_a_known_positive_lands_in_its_category(name: str, category: str, rules) -> None:
    """Extra turns and mass land denial have zero owned examples (A3).

    Zero hits over the pool confirms the collection holds none of either; it does
    not show the patterns are correct. This fixture is what tests them.
    """
    obj = next(o for o in KNOWN_POSITIVE if o["name"] == name)
    text = searchable(obj.get("type_line", ""), obj.get("oracle_text"), ())
    hit = rules.category(category)
    assert hit is not None
    assert hit.matches(name, text, type_line=obj.get("type_line", ""))


@pytest.mark.parametrize(("name", "category"), sorted(EXPECTED.items()))
def test_a_known_positive_lands_in_nothing_else(name: str, category: str, rules) -> None:
    obj = next(o for o in KNOWN_POSITIVE if o["name"] == name)
    text = searchable(obj.get("type_line", ""), obj.get("oracle_text"), ())
    matched = {
        c.name
        for c in rules.categories
        if c.matches(name, text, type_line=obj.get("type_line", ""))
    }
    assert matched == {category}


# --- the golden over the owned pool ---------------------------------------


def test_category_membership_over_the_pool_is_golden(rules) -> None:
    """A pattern edit shows as a diff and fails until the golden is regenerated.

    Regeneration is deliberate and puts the diff in front of a human. Nothing
    regenerates it automatically on failure — that is the mechanism (ADR-0009).
    """
    facts = read_facts(POOL)
    owned = [e for e in facts.cards if e.owned and e.card.legality == "legal"]
    membership = {
        category.name: sorted(e.card.name for e in owned if in_category(category, e))
        for category in rules.categories
    }
    golden = GOLDEN / "categories.json"
    rendered = json.dumps(membership, ensure_ascii=False, indent=2) + "\n"
    if regenerating():
        golden.write_text(rendered, encoding="utf-8")
        pytest.skip("golden regenerated by explicit request; review the diff")
    assert golden.exists(), "run with DECK_COMPOSER_REGENERATE_GOLDEN=1 to create it"
    assert json.loads(rendered) == json.loads(golden.read_text(encoding="utf-8"))


def test_the_violation_categories_are_empty_over_the_pool(rules) -> None:
    """A3: the collection holds no extra-turn card and no mass land denial."""
    facts = read_facts(POOL)
    owned = [e for e in facts.cards if e.owned and e.card.legality == "legal"]
    for category in rules.violations:
        assert [e.card.name for e in owned if in_category(category, e)] == []


def test_the_pool_sweepers_are_the_three_known_ones(rules) -> None:
    """By name, not by count: a bare count can agree with an unrelated error.

    Every sweeper in this collection is worded as damage to each creature, and
    all three are red — which is why a white-black deck's sweeper ceiling is
    genuinely zero forever rather than a gap in the pattern.
    """
    facts = read_facts(POOL)
    owned = [e for e in facts.cards if e.owned and e.card.legality == "legal"]
    sweepers = rules.category("sweepers")
    assert sweepers is not None
    found = {e.card.name for e in owned if in_category(sweepers, e)}
    assert found == {"Brotherhood's End", "Splatter Technique", "Wildfire Howl"}


def test_a_type_restricted_wrath_is_not_a_sweeper(rules) -> None:
    """Season of Gathering destroys all artifacts or all enchantments, never creatures."""
    facts = read_facts(POOL)
    season = facts.card("Season of Gathering")
    sweepers = rules.category("sweepers")
    assert season is not None and sweepers is not None
    assert not in_category(sweepers, season)


def test_a_land_is_never_ramp(rules) -> None:
    """A land that taps for mana is the mana base, not ramp."""
    facts = read_facts(POOL)
    ramp = rules.category("ramp")
    assert ramp is not None
    for entry in facts.cards:
        if "Land" in entry.card.type_line.split("//")[0]:
            assert not in_category(ramp, entry), entry.card.name


# --- the files ------------------------------------------------------------


def test_reminder_text_is_not_matched() -> None:
    """A parenthetical restates a rule the card does not itself do."""
    assert "surveil 2" in searchable("Sorcery", "Surveil 2. (Look at the top two cards.)", ())
    assert "look at the top" not in searchable("Sorcery", "Surveil 2. (Look at the top.)", ())


def test_the_rules_carry_their_provenance(rules) -> None:
    """A table must be able to say which bracket definition it was built under."""
    assert rules.version
    assert rules.content_hash.startswith("sha256:")
    assert rules.source["document"]
    assert rules.source["read"]


def test_targets_live_in_their_own_file() -> None:
    """A WotC update and a change of taste have different authorities."""
    targets = read_targets(TARGETS)
    assert targets.of("ramp") == {"min": 10}
    assert targets.of("sweepers") == {"min": 2}
    assert targets.of("lands") == {"min": 35, "max": 37}
    assert "extra_turns" not in targets.values


def test_only_violation_categories_carry_correction_lists() -> None:
    assert {c.kind for c in read_rules(CATEGORIES).categories} == {VIOLATION, METRIC}
    for category in read_rules(CATEGORIES).metrics:
        assert not category.include and not category.exclude


def test_a_correction_list_on_a_metric_is_rejected(tmp_path: Path) -> None:
    """Metrics never block, so maintaining lists for them is work with no payoff."""
    payload = json.loads(CATEGORIES.read_text(encoding="utf-8"))
    payload["categories"]["ramp"]["include"] = ["Sol Ring"]
    path = tmp_path / "categories.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    with pytest.raises(ToolError) as caught:
        read_rules(path)
    assert caught.value.error == "correction_list_on_a_metric"


def test_an_include_list_corrects_a_violation_pattern(tmp_path: Path) -> None:
    """A missed violation is a legality failure and needs a correction path."""
    payload = json.loads(CATEGORIES.read_text(encoding="utf-8"))
    payload["categories"]["extra_turns"]["include"] = ["Some Unreleased Card"]
    path = tmp_path / "categories.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    category = read_rules(path).category("extra_turns")
    assert category is not None
    assert category.matches("Some Unreleased Card", "does nothing at all")


def test_an_unknown_schema_fails_loudly(tmp_path: Path) -> None:
    path = tmp_path / "categories.json"
    path.write_text(json.dumps({"schema": 99}), encoding="utf-8")
    with pytest.raises(ToolError) as caught:
        read_rules(path)
    assert caught.value.error == "categories_schema_unknown"


def test_an_invalid_pattern_names_the_file_to_fix(tmp_path: Path) -> None:
    payload = json.loads(CATEGORIES.read_text(encoding="utf-8"))
    payload["categories"]["ramp"]["patterns"] = ["(unclosed"]
    path = tmp_path / "categories.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    with pytest.raises(ToolError) as caught:
        read_rules(path)
    assert caught.value.error == "pattern_invalid"
    assert "categories.json" in caught.value.next_step


def test_undecodable_categories_is_a_contract_failure(tmp_path: Path) -> None:
    path = tmp_path / "categories.json"
    path.write_bytes(b'{"schema": 1, "x": "\xff\xfe"}')
    with pytest.raises(ToolError) as caught:
        read_rules(path)
    assert caught.value.error == "categories_unreadable"
